# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=1.0.112
release_stage=ALPHA
group=dev.amble

# Dependencies
fabric_api_version=0.161.0+26.3
pal_version=1.2.7+mc.26.3
lambdynamiclights_version=4.13.0+26.3
fabric_kotlin_version=1.14.1+kotlin.2.4.20
fzzy_config_version=0.7.7+fix3+26.3
jei_version=31.9.0.58
voicechat_api_version=2.6.24
vosk_version=0.3.45
`