package dev.amble.client;

import dev.amble.client.effects.ArmedPose;
import dev.amble.client.effects.BeamEffects;
import dev.amble.client.effects.RemoteAim;
import dev.amble.client.effects.HealBeamEffects;
import dev.amble.client.effects.BlastEffects;
import dev.amble.client.effects.ConstructClient;
import dev.amble.client.effects.ElementAura;
import dev.amble.client.compat.IrisCompat;
import dev.amble.client.compat.ReplaySnapshot;
import dev.amble.client.config.BrightestDayClientConfig;
import dev.amble.client.effects.AbilityClient;
import dev.amble.client.effects.attacks.area.BarrageEffects;
import dev.amble.client.effects.attacks.area.NovaEffects;
import dev.amble.client.effects.attacks.area.SlamEffects;
import dev.amble.client.effects.attacks.projectile.ChainBoltEffects;
import dev.amble.client.effects.attacks.projectile.DiscEffects;
import dev.amble.client.effects.attacks.projectile.LanceEffects;
import dev.amble.client.effects.attacks.projectile.ProjectileBursts;
import dev.amble.client.effects.attacks.projectile.SwarmEffects;
import dev.amble.client.effects.attacks.utility.GrappleEffects;
import dev.amble.client.effects.attacks.utility.LumberjackEffects;
import dev.amble.client.effects.attacks.utility.OreProbeEffects;
import dev.amble.client.effects.attacks.weapon.FistEffects;
import dev.amble.client.effects.attacks.weapon.TurretEffects;
import dev.amble.client.effects.attacks.weapon.WhipEffects;
import dev.amble.client.effects.drill.DrillEffects;
import dev.amble.client.effects.drill.PlacedDrillEffects;
import dev.amble.client.effects.glide.GlideEffects;
import dev.amble.client.effects.AcidEffects;
import dev.amble.client.effects.ConcussiveEffects;
import dev.amble.client.effects.LightOrbEffects;
import dev.amble.client.effects.RingInput;
import dev.amble.client.effects.ScanEffects;
import dev.amble.client.effects.SpotlightEffects;
import dev.amble.client.effects.SculptClient;
import dev.amble.client.wheel.PowerWheel;
import dev.amble.client.effects.ShieldEffects;
import dev.amble.client.effects.TractorEffects;
import dev.amble.client.effects.SphereEffects;
import dev.amble.client.effects.PoseAnimations;
import dev.amble.client.effects.InsigniaEffects;
import dev.amble.client.poses.PoseLibrary;
import dev.amble.client.effects.CompassEffects;
import dev.amble.client.hud.SyncHud;
import dev.amble.client.effects.WallEffects;
import dev.amble.client.effects.BatteryEffects;
import dev.amble.client.effects.LanternChargeAnimations;
import dev.amble.client.effects.BloodHuntClient;
import dev.amble.client.effects.CommsClient;
import dev.amble.client.effects.MegaphoneClient;
import dev.amble.client.effects.SanctuaryEffects;
import dev.amble.client.forge.ForgeClient;
import dev.amble.client.forge.ForgeHammerHud;
import dev.amble.client.flight.FlightAnimations;
import dev.amble.client.flight.FlightAnimator;
import dev.amble.client.flight.AileronRolls;
import dev.amble.client.team.ClientTeams;
import dev.amble.client.flight.FlightTrail;
import dev.amble.client.hud.FlightSpeedHud;
import dev.amble.client.hud.EmotionVignette;
import dev.amble.client.hud.PilgrimageHud;
import dev.amble.client.hud.RingChargeHud;
import dev.amble.client.hud.OathHud;
import dev.amble.client.hud.RingFeed;
import dev.amble.client.render.LanternBlockEntityRenderer;
import dev.amble.client.render.GlowAura;
import dev.amble.client.render.LanternSuit;
import dev.amble.client.render.SuitGlowLayer;
import dev.amble.client.render.InsigniaLayer;
import dev.amble.client.render.BatteryTextures;
import dev.amble.client.render.Holograms;
import dev.amble.client.render.SlottedRingLayer;
import dev.amble.client.screens.LanternButtons;
import dev.amble.client.screens.LanternScreen;
import dev.amble.client.screens.OfficialServerButton;
import dev.amble.client.screens.MannequinScreen;
import dev.amble.core.BrightestDayBlockEntityTypes;
import dev.amble.core.BrightestDayMenus;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.client.rendering.v1.BlockEntityRendererRegistry;
import net.fabricmc.fabric.api.client.rendering.v1.LivingEntityRenderLayerRegistrationCallback;
import net.fabricmc.fabric.api.client.rendering.v1.BlockColorRegistry;
import dev.amble.core.BrightestDayBlocks;
import net.minecraft.client.color.block.BlockTintSources;
import net.minecraft.client.gui.screens.MenuScreens;
import net.minecraft.client.renderer.entity.player.AvatarRenderer;

import java.util.List;

public class BrightestDayClient implements ClientModInitializer {
    private static final int CRYSTAL_TINT = 0xFFFFA0E8;

    @Override
    public void onInitializeClient() {
        BrightestDayClientConfig.load();
        BrightestDayKeybinds.init();
        FlightAnimator.init();
        FlightAnimations.init();
        LanternChargeAnimations.init();
        PoseAnimations.init();
        PoseLibrary.init();
        InsigniaEffects.init();
        BatteryTextures.init();
        Holograms.init();
        BlockColorRegistry.register(List.of(BlockTintSources.constant(CRYSTAL_TINT)), BrightestDayBlocks.ZAMARON_CRYSTAL_CLUSTER);
        FlightTrail.init();
        AileronRolls.init();
        ClientTeams.init();
        BlastEffects.init();
        ShieldEffects.init();
        WallEffects.init();
        BatteryEffects.init();
        SanctuaryEffects.init();
        BloodHuntClient.init();
        CommsClient.init();
        MegaphoneClient.init();
        BeamEffects.init();
        RemoteAim.init();
        HealBeamEffects.init();
        ArmedPose.init();
        ElementAura.init();
        TractorEffects.init();
        SphereEffects.init();
        CompassEffects.init();
        ScanEffects.init();
        GlowAura.init();
        LanternSuit.init();
        ForgeClient.init();
        ForgeHammerHud.init();
        ConstructClient.init();
        SculptClient.init();
        PowerWheel.init();
        RingFeed.init();
        SyncHud.init();
        OathHud.init();
        RingInput.init();
        AbilityClient.init();
        ConcussiveEffects.init();
        NovaEffects.init();
        SlamEffects.init();
        BarrageEffects.init();
        FistEffects.init();
        WhipEffects.init();
        TurretEffects.init();
        ProjectileBursts.init();
        SwarmEffects.init();
        LanceEffects.init();
        ChainBoltEffects.init();
        DiscEffects.init();
        DrillEffects.init();
        PlacedDrillEffects.init();
        GlideEffects.init();
        GrappleEffects.init();
        LumberjackEffects.init();
        OreProbeEffects.init();
        AcidEffects.init();
        LightOrbEffects.init();
        SpotlightEffects.init();
        ReplaySnapshot.init();
        IrisCompat.init();
        LanternButtons.init();
        OfficialServerButton.init();
        RingChargeHud.init();
        EmotionVignette.init();
        PilgrimageHud.init();
        FlightSpeedHud.init();
        MenuScreens.register(BrightestDayMenus.LANTERN, LanternScreen::new);
        MenuScreens.register(BrightestDayMenus.MANNEQUIN, MannequinScreen::new);
        LivingEntityRenderLayerRegistrationCallback.EVENT.register((entityType, entityRenderer, helper, context) -> {
            if (entityRenderer instanceof AvatarRenderer<?> avatarRenderer) {
                helper.register(new SlottedRingLayer(avatarRenderer));
                helper.register(new SuitGlowLayer(avatarRenderer));
                helper.register(new InsigniaLayer(avatarRenderer));
            }
        });
        registerBlockEntityRenderers();
    }

    private void registerBlockEntityRenderers() {
        BlockEntityRendererRegistry.register(BrightestDayBlockEntityTypes.LANTERN_BLOCK_ENTITY_TYPE, LanternBlockEntityRenderer::new);
    }
}
