package dev.amble.client.config;

import dev.amble.config.BrightestDayConfig;
import dev.isxander.yacl3.api.ConfigCategory;
import dev.isxander.yacl3.api.Option;
import dev.isxander.yacl3.api.OptionDescription;
import dev.isxander.yacl3.api.OptionGroup;
import dev.isxander.yacl3.api.YetAnotherConfigLib;
import dev.isxander.yacl3.api.controller.DoubleSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.FloatSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import org.jspecify.annotations.Nullable;

import java.util.function.Consumer;
import java.util.function.Supplier;

public final class BrightestDayConfigScreen {
    private static final String PREFIX = "config.brightestday.";

    private BrightestDayConfigScreen() {}

    public static Screen create(@Nullable Screen parent) {
        return YetAnotherConfigLib.create(BrightestDayConfig.HANDLER, (defaults, config, builder) -> builder
                .title(Component.translatable(PREFIX + "title"))
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable(PREFIX + "category.constructs"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.blast"))
                                .option(intSlider("blast_cost", defaults.blastCost, () -> config.blastCost, v -> config.blastCost = v, 0, 1000, 10))
                                .option(doubleSlider("blast_range", defaults.blastRange, () -> config.blastRange, v -> config.blastRange = v, 8.0, 128.0, 1.0))
                                .option(doubleSlider("blast_radius", defaults.blastRadius, () -> config.blastRadius, v -> config.blastRadius = v, 1.0, 16.0, 0.5))
                                .option(floatSlider("blast_direct_damage", defaults.blastDirectDamage, () -> config.blastDirectDamage, v -> config.blastDirectDamage = v, 0.0F, 40.0F, 0.5F))
                                .option(floatSlider("blast_splash_damage", defaults.blastSplashDamage, () -> config.blastSplashDamage, v -> config.blastSplashDamage = v, 0.0F, 40.0F, 0.5F))
                                .option(doubleSlider("blast_knockback", defaults.blastKnockback, () -> config.blastKnockback, v -> config.blastKnockback = v, 0.0, 5.0, 0.1))
                                .option(floatSlider("blast_explosion_power", defaults.blastExplosionPower, () -> config.blastExplosionPower, v -> config.blastExplosionPower = v, 0.0F, 8.0F, 0.1F))
                                .option(toggle("blast_breaks_blocks", defaults.blastBreaksBlocks, () -> config.blastBreaksBlocks, v -> config.blastBreaksBlocks = v))
                                .option(doubleSlider("blast_assist_cone", defaults.blastAssistConeDegrees, () -> config.blastAssistConeDegrees, v -> config.blastAssistConeDegrees = v, 0.0, 45.0, 1.0))
                                .option(doubleSlider("blast_homing_cone", defaults.blastHomingConeDegrees, () -> config.blastHomingConeDegrees, v -> config.blastHomingConeDegrees = v, 0.0, 90.0, 1.0))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.beam"))
                                .option(floatSlider("beam_damage", defaults.beamDamage, () -> config.beamDamage, v -> config.beamDamage = v, 0.0F, 20.0F, 0.5F))
                                .option(intSlider("beam_max_ticks", defaults.beamMaxTicks, () -> config.beamMaxTicks, v -> config.beamMaxTicks = v, 20, 600, 10))
                                .option(intSlider("beam_drain", defaults.beamDrainPerSecond, () -> config.beamDrainPerSecond, v -> config.beamDrainPerSecond = v, 0, 200, 1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.heal_beam"))
                                .option(floatSlider("heal_beam_amount", defaults.healBeamAmount, () -> config.healBeamAmount, v -> config.healBeamAmount = v, 0.0F, 10.0F, 0.5F))
                                .option(intSlider("heal_beam_max_ticks", defaults.healBeamMaxTicks, () -> config.healBeamMaxTicks, v -> config.healBeamMaxTicks = v, 20, 1200, 10))
                                .option(intSlider("heal_beam_drain", defaults.healBeamDrainPerSecond, () -> config.healBeamDrainPerSecond, v -> config.healBeamDrainPerSecond = v, 0, 200, 1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.wall"))
                                .option(intSlider("wall_lifetime", defaults.wallLifetimeTicks, () -> config.wallLifetimeTicks, v -> config.wallLifetimeTicks = v, 20, 6000, 20))
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable(PREFIX + "category.sculpt"))
                        .option(intSlider("sculpt_block_cost", defaults.sculptBlockCost, () -> config.sculptBlockCost, v -> config.sculptBlockCost = v, 0, 20, 1))
                        .option(intField("sculpt_max_blocks", defaults.sculptMaxBlocks, () -> config.sculptMaxBlocks, v -> config.sculptMaxBlocks = v, 1, 65536))
                        .option(intField("sculpt_max_total_blocks", defaults.sculptMaxTotalBlocks, () -> config.sculptMaxTotalBlocks, v -> config.sculptMaxTotalBlocks = v, 1, 262144))
                        .option(intField("sculpt_blocks_per_upkeep", defaults.sculptBlocksPerUpkeep, () -> config.sculptBlocksPerUpkeep, v -> config.sculptBlocksPerUpkeep = v, 1, 65536))
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable(PREFIX + "category.ring"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.charge"))
                                .description(OptionDescription.of(Component.translatable(PREFIX + "group.charge.desc")))
                                .option(intSlider("charge_blast", defaults.blastChargeTicks, () -> config.blastChargeTicks, v -> config.blastChargeTicks = v, 0, 100, 1))
                                .option(intSlider("charge_beam", defaults.beamChargeTicks, () -> config.beamChargeTicks, v -> config.beamChargeTicks = v, 0, 100, 1))
                                .option(intSlider("charge_heal_beam", defaults.healBeamChargeTicks, () -> config.healBeamChargeTicks, v -> config.healBeamChargeTicks = v, 0, 100, 1))
                                .option(intSlider("charge_entity_shield", defaults.entityShieldChargeTicks, () -> config.entityShieldChargeTicks, v -> config.entityShieldChargeTicks = v, 0, 100, 1))
                                .option(intSlider("charge_area_shield", defaults.areaShieldChargeTicks, () -> config.areaShieldChargeTicks, v -> config.areaShieldChargeTicks = v, 0, 100, 1))
                                .option(intSlider("charge_wall", defaults.wallChargeTicks, () -> config.wallChargeTicks, v -> config.wallChargeTicks = v, 0, 100, 1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.concussive"))
                                .option(doubleSlider("concussive_range", defaults.concussiveRange, () -> config.concussiveRange, v -> config.concussiveRange = v, 1.0, 24.0, 0.5))
                                .option(doubleSlider("concussive_cone", defaults.concussiveConeDegrees, () -> config.concussiveConeDegrees, v -> config.concussiveConeDegrees = v, 5.0, 180.0, 5.0))
                                .option(doubleSlider("concussive_knockback", defaults.concussiveKnockback, () -> config.concussiveKnockback, v -> config.concussiveKnockback = v, 0.0, 6.0, 0.1))
                                .option(floatSlider("concussive_damage", defaults.concussiveDamage, () -> config.concussiveDamage, v -> config.concussiveDamage = v, 0.0F, 20.0F, 0.5F))
                                .option(intSlider("concussive_cost", defaults.concussiveCost, () -> config.concussiveCost, v -> config.concussiveCost = v, 0, 500, 5))
                                .option(intSlider("concussive_cooldown", defaults.concussiveCooldownTicks, () -> config.concussiveCooldownTicks, v -> config.concussiveCooldownTicks = v, 0, 200, 1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.flight"))
                                .option(doubleSlider("flight_boost_multiplier", defaults.flightBoostMultiplier, () -> config.flightBoostMultiplier, v -> config.flightBoostMultiplier = v, 1.0, 5.0, 0.1))
                                .option(doubleSlider("flight_max_boost_speed", defaults.flightMaxBoostSpeed, () -> config.flightMaxBoostSpeed, v -> config.flightMaxBoostSpeed = v, 1.0, 10.0, 0.1))
                                .option(intSlider("flight_drain", defaults.flightDrainPerSecond, () -> config.flightDrainPerSecond, v -> config.flightDrainPerSecond = v, 0, 100, 1))
                                .option(intSlider("flight_boost_drain", defaults.flightBoostDrainPerSecond, () -> config.flightBoostDrainPerSecond, v -> config.flightBoostDrainPerSecond = v, 0, 200, 1))
                                .option(toggle("show_flight_speedometer", defaults.showFlightSpeedometer, () -> config.showFlightSpeedometer, v -> config.showFlightSpeedometer = v))
                                .option(toggle("show_flight_trails", defaults.showFlightTrails, () -> config.showFlightTrails, v -> config.showFlightTrails = v))
                                .option(toggle("aileron_rolls", defaults.aileronRolls, () -> config.aileronRolls, v -> config.aileronRolls = v))
                                .option(doubleSlider("aileron_roll_dodge", defaults.aileronRollDodge, () -> config.aileronRollDodge, v -> config.aileronRollDodge = v, 0.0, 4.0, 0.1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.synergy"))
                                .option(doubleSlider("synergy_link_radius", defaults.synergyLinkRadius, () -> config.synergyLinkRadius, v -> config.synergyLinkRadius = v, 8.0, 256.0, 4.0))
                                .option(doubleSlider("synergy_dread_radius", defaults.synergyDreadRadius, () -> config.synergyDreadRadius, v -> config.synergyDreadRadius = v, 4.0, 128.0, 1.0))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.loyalty"))
                                .option(intSlider("ring_loyalty_deaths", defaults.ringLoyaltyDeaths, () -> config.ringLoyaltyDeaths, v -> config.ringLoyaltyDeaths = v, 0, 20, 1))
                                .option(doubleSlider("ring_loyalty_search_radius", defaults.ringLoyaltySearchRadius, () -> config.ringLoyaltySearchRadius, v -> config.ringLoyaltySearchRadius = v, 16.0, 4096.0, 16.0))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.team"))
                                .option(doubleSlider("team_invite_range", defaults.teamInviteRange, () -> config.teamInviteRange, v -> config.teamInviteRange = v, 8.0, 256.0, 4.0))
                                .option(intSlider("team_max_size", defaults.teamMaxSize, () -> config.teamMaxSize, v -> config.teamMaxSize = v, 2, 16, 1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.space"))
                                .option(doubleSlider("space_entry_height", defaults.spaceEntryHeight, () -> config.spaceEntryHeight, v -> config.spaceEntryHeight = v, 320.0, 2048.0, 8.0))
                                .option(doubleSlider("space_arrival_height", defaults.spaceArrivalHeight, () -> config.spaceArrivalHeight, v -> config.spaceArrivalHeight = v, 100.0, 380.0, 5.0))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.glider"))
                                .option(intSlider("glider_cost", defaults.gliderCost, () -> config.gliderCost, v -> config.gliderCost = v, 0, 1000, 5))
                                .option(intSlider("glider_charge", defaults.gliderChargeTicks, () -> config.gliderChargeTicks, v -> config.gliderChargeTicks = v, 0, 100, 1))
                                .option(intField("glider_duration", defaults.gliderDurationTicks, () -> config.gliderDurationTicks, v -> config.gliderDurationTicks = v, 20, 12000))
                                .option(doubleSlider("glider_range", defaults.gliderRange, () -> config.gliderRange, v -> config.gliderRange = v, 4.0, 128.0, 1.0))
                                .option(doubleSlider("glider_assist_cone", defaults.gliderAssistConeDegrees, () -> config.gliderAssistConeDegrees, v -> config.gliderAssistConeDegrees = v, 0.0, 45.0, 1.0))
                                .option(doubleSlider("glider_mob_fall_speed", defaults.gliderMobFallSpeed, () -> config.gliderMobFallSpeed, v -> config.gliderMobFallSpeed = v, 0.02, 1.0, 0.01))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.drill"))
                                .option(intSlider("drill_cost", defaults.drillCost, () -> config.drillCost, v -> config.drillCost = v, 0, 1000, 5))
                                .option(intSlider("drill_charge", defaults.drillChargeTicks, () -> config.drillChargeTicks, v -> config.drillChargeTicks = v, 0, 100, 1))
                                .option(floatSlider("drill_speed", defaults.drillSpeed, () -> config.drillSpeed, v -> config.drillSpeed = v, 1.0F, 60.0F, 0.5F))
                                .option(intSlider("drill_drain", defaults.drillDrainPerSecond, () -> config.drillDrainPerSecond, v -> config.drillDrainPerSecond = v, 0, 200, 1))
                                .option(intSlider("drill_drain_per_size", defaults.drillDrainPerSize, () -> config.drillDrainPerSize, v -> config.drillDrainPerSize = v, 0, 100, 1))
                                .option(intSlider("drill_placed_max", defaults.drillPlacedMaxCount, () -> config.drillPlacedMaxCount, v -> config.drillPlacedMaxCount = v, 1, 16, 1))
                                .option(intSlider("drill_placed_distance", defaults.drillPlacedDistance, () -> config.drillPlacedDistance, v -> config.drillPlacedDistance = v, 1, 128, 1))
                                .option(intSlider("drill_placed_lifetime", defaults.drillPlacedLifetimeTicks, () -> config.drillPlacedLifetimeTicks, v -> config.drillPlacedLifetimeTicks = v, 20, 6000, 20))
                                .option(intSlider("drill_placed_travel", defaults.drillPlacedTravelTicks, () -> config.drillPlacedTravelTicks, v -> config.drillPlacedTravelTicks = v, 1, 40, 1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.light"))
                                .option(intSlider("light_orb_cost", defaults.lightOrbCost, () -> config.lightOrbCost, v -> config.lightOrbCost = v, 0, 500, 5))
                                .option(intSlider("light_orb_charge", defaults.lightOrbChargeTicks, () -> config.lightOrbChargeTicks, v -> config.lightOrbChargeTicks = v, 0, 100, 1))
                                .option(intSlider("light_orb_upkeep", defaults.lightOrbUpkeepPerSize, () -> config.lightOrbUpkeepPerSize, v -> config.lightOrbUpkeepPerSize = v, 0, 50, 1))
                                .option(intSlider("light_orb_max", defaults.lightOrbMaxCount, () -> config.lightOrbMaxCount, v -> config.lightOrbMaxCount = v, 1, 64, 1))
                                .option(doubleSlider("spotlight_range", defaults.spotlightRange, () -> config.spotlightRange, v -> config.spotlightRange = v, 8.0, 128.0, 1.0))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.acid"))
                                .option(doubleSlider("acid_range", defaults.acidRange, () -> config.acidRange, v -> config.acidRange = v, 1.0, 16.0, 0.5))
                                .option(floatSlider("acid_damage", defaults.acidDamage, () -> config.acidDamage, v -> config.acidDamage = v, 0.0F, 20.0F, 0.5F))
                                .option(intSlider("acid_fire_seconds", defaults.acidFireSeconds, () -> config.acidFireSeconds, v -> config.acidFireSeconds = v, 0, 20, 1))
                                .option(intSlider("acid_armor_wear", defaults.acidArmorWear, () -> config.acidArmorWear, v -> config.acidArmorWear = v, 0, 20, 1))
                                .option(intSlider("acid_drain", defaults.acidDrainPerSecond, () -> config.acidDrainPerSecond, v -> config.acidDrainPerSecond = v, 0, 200, 1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.self_heal"))
                                .option(floatSlider("self_heal_amount", defaults.selfHealAmount, () -> config.selfHealAmount, v -> config.selfHealAmount = v, 0.0F, 10.0F, 0.5F))
                                .option(intSlider("self_heal_interval", defaults.selfHealIntervalTicks, () -> config.selfHealIntervalTicks, v -> config.selfHealIntervalTicks = v, 1, 200, 1))
                                .option(intSlider("self_heal_drain", defaults.selfHealDrainPerSecond, () -> config.selfHealDrainPerSecond, v -> config.selfHealDrainPerSecond = v, 0, 100, 1))
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Component.translatable(PREFIX + "category.attacks"))
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.swarm_missiles"))
                                .option(intSlider("swarm_cost", defaults.swarmCost, () -> config.swarmCost, v -> config.swarmCost = v, 0, 1000, 10))
                                .option(intSlider("swarm_charge", defaults.swarmChargeTicks, () -> config.swarmChargeTicks, v -> config.swarmChargeTicks = v, 0, 100, 1))
                                .option(intSlider("swarm_darts", defaults.swarmDarts, () -> config.swarmDarts, v -> config.swarmDarts = v, 1, 16, 1))
                                .option(floatSlider("swarm_damage", defaults.swarmDamage, () -> config.swarmDamage, v -> config.swarmDamage = v, 0.0F, 20.0F, 0.5F))
                                .option(doubleSlider("swarm_range", defaults.swarmRange, () -> config.swarmRange, v -> config.swarmRange = v, 4.0, 96.0, 1.0))
                                .option(doubleSlider("swarm_cone", defaults.swarmConeDegrees, () -> config.swarmConeDegrees, v -> config.swarmConeDegrees = v, 5.0, 180.0, 5.0))
                                .option(doubleSlider("swarm_knockback", defaults.swarmKnockback, () -> config.swarmKnockback, v -> config.swarmKnockback = v, 0.0, 3.0, 0.05))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.piercing_lance"))
                                .option(intSlider("lance_cost", defaults.lanceCost, () -> config.lanceCost, v -> config.lanceCost = v, 0, 1000, 10))
                                .option(intSlider("lance_charge", defaults.lanceChargeTicks, () -> config.lanceChargeTicks, v -> config.lanceChargeTicks = v, 0, 100, 1))
                                .option(floatSlider("lance_damage", defaults.lanceDamage, () -> config.lanceDamage, v -> config.lanceDamage = v, 0.0F, 60.0F, 0.5F))
                                .option(doubleSlider("lance_range", defaults.lanceRange, () -> config.lanceRange, v -> config.lanceRange = v, 8.0, 128.0, 1.0))
                                .option(doubleSlider("lance_knockback", defaults.lanceKnockback, () -> config.lanceKnockback, v -> config.lanceKnockback = v, 0.0, 3.0, 0.05))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.chain_bolt"))
                                .option(intSlider("chain_cost", defaults.chainCost, () -> config.chainCost, v -> config.chainCost = v, 0, 1000, 10))
                                .option(intSlider("chain_charge", defaults.chainChargeTicks, () -> config.chainChargeTicks, v -> config.chainChargeTicks = v, 0, 100, 1))
                                .option(floatSlider("chain_damage", defaults.chainDamage, () -> config.chainDamage, v -> config.chainDamage = v, 0.0F, 40.0F, 0.5F))
                                .option(doubleSlider("chain_range", defaults.chainRange, () -> config.chainRange, v -> config.chainRange = v, 4.0, 96.0, 1.0))
                                .option(intSlider("chain_max_jumps", defaults.chainMaxJumps, () -> config.chainMaxJumps, v -> config.chainMaxJumps = v, 0, 14, 1))
                                .option(floatSlider("chain_falloff", defaults.chainFalloff, () -> config.chainFalloff, v -> config.chainFalloff = v, 0.1F, 1.0F, 0.05F))
                                .option(doubleSlider("chain_jump_range", defaults.chainJumpRange, () -> config.chainJumpRange, v -> config.chainJumpRange = v, 1.0, 24.0, 0.5))
                                .option(doubleSlider("chain_knockback", defaults.chainKnockback, () -> config.chainKnockback, v -> config.chainKnockback = v, 0.0, 3.0, 0.05))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.boomerang_disc"))
                                .option(intSlider("disc_cost", defaults.discCost, () -> config.discCost, v -> config.discCost = v, 0, 1000, 10))
                                .option(intSlider("disc_charge", defaults.discChargeTicks, () -> config.discChargeTicks, v -> config.discChargeTicks = v, 0, 100, 1))
                                .option(floatSlider("disc_damage", defaults.discDamage, () -> config.discDamage, v -> config.discDamage = v, 0.0F, 40.0F, 0.5F))
                                .option(doubleSlider("disc_range", defaults.discRange, () -> config.discRange, v -> config.discRange = v, 4.0, 64.0, 1.0))
                                .option(doubleSlider("disc_knockback", defaults.discKnockback, () -> config.discKnockback, v -> config.discKnockback = v, 0.0, 3.0, 0.05))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.nova_burst"))
                                .option(intSlider("nova_cost", defaults.novaCost, () -> config.novaCost, v -> config.novaCost = v, 0, 1000, 10))
                                .option(intSlider("nova_charge", defaults.novaChargeTicks, () -> config.novaChargeTicks, v -> config.novaChargeTicks = v, 0, 100, 1))
                                .option(floatSlider("nova_damage", defaults.novaDamage, () -> config.novaDamage, v -> config.novaDamage = v, 0.0F, 60.0F, 0.5F))
                                .option(doubleSlider("nova_radius", defaults.novaRadius, () -> config.novaRadius, v -> config.novaRadius = v, 1.0, 24.0, 0.5))
                                .option(doubleSlider("nova_knockback", defaults.novaKnockback, () -> config.novaKnockback, v -> config.novaKnockback = v, 0.0, 6.0, 0.1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.ground_slam"))
                                .option(intSlider("slam_cost", defaults.slamCost, () -> config.slamCost, v -> config.slamCost = v, 0, 1000, 10))
                                .option(intSlider("slam_charge", defaults.slamChargeTicks, () -> config.slamChargeTicks, v -> config.slamChargeTicks = v, 0, 100, 1))
                                .option(floatSlider("slam_base_damage", defaults.slamBaseDamage, () -> config.slamBaseDamage, v -> config.slamBaseDamage = v, 0.0F, 40.0F, 0.5F))
                                .option(floatSlider("slam_damage_per_block", defaults.slamDamagePerBlock, () -> config.slamDamagePerBlock, v -> config.slamDamagePerBlock = v, 0.0F, 2.0F, 0.05F))
                                .option(floatSlider("slam_max_damage", defaults.slamMaxDamage, () -> config.slamMaxDamage, v -> config.slamMaxDamage = v, 0.0F, 60.0F, 0.5F))
                                .option(doubleSlider("slam_min_radius", defaults.slamMinRadius, () -> config.slamMinRadius, v -> config.slamMinRadius = v, 1.0, 24.0, 0.5))
                                .option(doubleSlider("slam_max_radius", defaults.slamMaxRadius, () -> config.slamMaxRadius, v -> config.slamMaxRadius = v, 1.0, 32.0, 0.5))
                                .option(doubleSlider("slam_radius_per_block", defaults.slamRadiusPerBlock, () -> config.slamRadiusPerBlock, v -> config.slamRadiusPerBlock = v, 0.0, 1.0, 0.05))
                                .option(doubleSlider("slam_launch", defaults.slamLaunch, () -> config.slamLaunch, v -> config.slamLaunch = v, 0.0, 4.0, 0.1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.rapid_barrage"))
                                .option(intSlider("barrage_cost", defaults.barrageCost, () -> config.barrageCost, v -> config.barrageCost = v, 0, 1000, 10))
                                .option(intSlider("barrage_charge", defaults.barrageChargeTicks, () -> config.barrageChargeTicks, v -> config.barrageChargeTicks = v, 0, 100, 1))
                                .option(floatSlider("barrage_damage", defaults.barrageDamage, () -> config.barrageDamage, v -> config.barrageDamage = v, 0.0F, 20.0F, 0.5F))
                                .option(doubleSlider("barrage_range", defaults.barrageRange, () -> config.barrageRange, v -> config.barrageRange = v, 4.0, 96.0, 1.0))
                                .option(intSlider("barrage_fire_interval", defaults.barrageFireInterval, () -> config.barrageFireInterval, v -> config.barrageFireInterval = v, 1, 40, 1))
                                .option(intSlider("barrage_max_ticks", defaults.barrageMaxTicks, () -> config.barrageMaxTicks, v -> config.barrageMaxTicks = v, 20, 1200, 10))
                                .option(intSlider("barrage_drain", defaults.barrageDrainPerSecond, () -> config.barrageDrainPerSecond, v -> config.barrageDrainPerSecond = v, 0, 200, 1))
                                .option(doubleSlider("barrage_spread", defaults.barrageSpreadDegrees, () -> config.barrageSpreadDegrees, v -> config.barrageSpreadDegrees = v, 0.0, 15.0, 0.1))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.giant_fist"))
                                .option(intSlider("fist_cost", defaults.fistCost, () -> config.fistCost, v -> config.fistCost = v, 0, 1000, 10))
                                .option(intSlider("fist_charge", defaults.fistChargeTicks, () -> config.fistChargeTicks, v -> config.fistChargeTicks = v, 0, 100, 1))
                                .option(floatSlider("fist_damage", defaults.fistDamage, () -> config.fistDamage, v -> config.fistDamage = v, 0.0F, 60.0F, 0.5F))
                                .option(doubleSlider("fist_range", defaults.fistRange, () -> config.fistRange, v -> config.fistRange = v, 1.0, 24.0, 0.5))
                                .option(doubleSlider("fist_knockback", defaults.fistKnockback, () -> config.fistKnockback, v -> config.fistKnockback = v, 0.0, 6.0, 0.1))
                                .option(doubleSlider("fist_impact_radius", defaults.fistImpactRadius, () -> config.fistImpactRadius, v -> config.fistImpactRadius = v, 0.0, 8.0, 0.25))
                                .option(floatSlider("fist_impact_damage", defaults.fistImpactDamage, () -> config.fistImpactDamage, v -> config.fistImpactDamage = v, 0.0F, 40.0F, 0.5F))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.energy_whip"))
                                .option(intSlider("whip_cost", defaults.whipCost, () -> config.whipCost, v -> config.whipCost = v, 0, 1000, 10))
                                .option(intSlider("whip_charge", defaults.whipChargeTicks, () -> config.whipChargeTicks, v -> config.whipChargeTicks = v, 0, 100, 1))
                                .option(floatSlider("whip_damage", defaults.whipDamage, () -> config.whipDamage, v -> config.whipDamage = v, 0.0F, 40.0F, 0.5F))
                                .option(doubleSlider("whip_length", defaults.whipLength, () -> config.whipLength, v -> config.whipLength = v, 2.0, 24.0, 0.5))
                                .option(floatSlider("whip_arc", defaults.whipArcDegrees, () -> config.whipArcDegrees, v -> config.whipArcDegrees = v, 10.0F, 360.0F, 5.0F))
                                .option(doubleSlider("whip_knockback", defaults.whipKnockback, () -> config.whipKnockback, v -> config.whipKnockback = v, 0.0, 6.0, 0.1))
                                .option(doubleSlider("whip_lash_length", defaults.whipLashLength, () -> config.whipLashLength, v -> config.whipLashLength = v, 2.0, 32.0, 0.5))
                                .option(floatSlider("whip_lash_damage", defaults.whipLashDamage, () -> config.whipLashDamage, v -> config.whipLashDamage = v, 0.0F, 40.0F, 0.5F))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Component.translatable(PREFIX + "group.sentry_turret"))
                                .option(intSlider("turret_cost", defaults.turretCost, () -> config.turretCost, v -> config.turretCost = v, 0, 1000, 10))
                                .option(intSlider("turret_charge", defaults.turretChargeTicks, () -> config.turretChargeTicks, v -> config.turretChargeTicks = v, 0, 100, 1))
                                .option(intSlider("turret_lifetime", defaults.turretLifetimeTicks, () -> config.turretLifetimeTicks, v -> config.turretLifetimeTicks = v, 20, 6000, 20))
                                .option(intSlider("turret_max", defaults.turretMaxCount, () -> config.turretMaxCount, v -> config.turretMaxCount = v, 1, 16, 1))
                                .option(doubleSlider("turret_range", defaults.turretRange, () -> config.turretRange, v -> config.turretRange = v, 4.0, 64.0, 1.0))
                                .option(intSlider("turret_fire_interval", defaults.turretFireInterval, () -> config.turretFireInterval, v -> config.turretFireInterval = v, 1, 200, 1))
                                .option(floatSlider("turret_bolt_damage", defaults.turretBoltDamage, () -> config.turretBoltDamage, v -> config.turretBoltDamage = v, 0.0F, 20.0F, 0.5F))
                                .build())
                        .build())
        ).generateScreen(parent);
    }

    private static <T> Option.Builder<T> option(String key, T def, Supplier<T> getter, Consumer<T> setter) {
        return Option.<T>createBuilder()
                .name(Component.translatable(PREFIX + "option." + key))
                .description(OptionDescription.of(Component.translatable(PREFIX + "option." + key + ".desc")))
                .binding(def, getter, setter);
    }

    private static Option<Boolean> toggle(String key, boolean def, Supplier<Boolean> getter, Consumer<Boolean> setter) {
        return option(key, def, getter, setter)
                .controller(TickBoxControllerBuilder::create)
                .build();
    }

    private static Option<Integer> intSlider(String key, int def, Supplier<Integer> getter, Consumer<Integer> setter, int min, int max, int step) {
        return option(key, def, getter, setter)
                .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(min, max).step(step))
                .build();
    }

    private static Option<Integer> intField(String key, int def, Supplier<Integer> getter, Consumer<Integer> setter, int min, int max) {
        return option(key, def, getter, setter)
                .controller(opt -> IntegerFieldControllerBuilder.create(opt).range(min, max))
                .build();
    }

    private static Option<Float> floatSlider(String key, float def, Supplier<Float> getter, Consumer<Float> setter, float min, float max, float step) {
        return option(key, def, getter, setter)
                .controller(opt -> FloatSliderControllerBuilder.create(opt).range(min, max).step(step))
                .build();
    }

    private static Option<Double> doubleSlider(String key, double def, Supplier<Double> getter, Consumer<Double> setter, double min, double max, double step) {
        return option(key, def, getter, setter)
                .controller(opt -> DoubleSliderControllerBuilder.create(opt).range(min, max).step(step))
                .build();
    }
}
