package dev.amble;

import dev.amble.config.BrightestDayConfig;
import dev.amble.core.BrightestDayAttachments;
import dev.amble.core.BrightestDayBlockEntityTypes;
import dev.amble.core.BrightestDayBlocks;
import dev.amble.core.BrightestDayCreativeTabs;
import dev.amble.core.BrightestDayItems;
import dev.amble.core.mannequin.Mannequins;
import dev.amble.core.BrightestDayMenus;
import dev.amble.core.BrightestDaySounds;
import dev.amble.core.networking.Networking;
import dev.amble.core.comms.Comms;
import dev.amble.core.comms.Megaphone;
import dev.amble.core.oath.OathCharge;
import dev.amble.core.ringpowers.BloodHunt;
import dev.amble.core.ringpowers.CometRam;
import dev.amble.core.ringpowers.RedRage;
import dev.amble.core.ringpowers.RingPowerRegistry;
import dev.amble.core.ringpowers.RingPowerTicker;
import dev.amble.core.ringpowers.impl.FlightRingPower;
import dev.amble.core.shields.ShieldManager;
import dev.amble.core.tractor.TractorManager;
import dev.amble.core.sphere.ContainmentSphere;
import dev.amble.core.mounts.ConstructMounts;
import dev.amble.core.sync.RingSync;
import dev.amble.core.sync.RingCompass;
import dev.amble.core.forge.BatteryRitual;
import dev.amble.core.poses.Poses;
import dev.amble.core.visuals.Insignia;
import dev.amble.core.ringpowers.constructs.ConstructTools;
import dev.amble.core.ringpowers.constructs.ConstructDismissal;
import dev.amble.core.walls.WallManager;
import dev.amble.core.sculpt.SculptManager;
import dev.amble.core.ringpowers.RingJumpstart;
import dev.amble.core.acid.AcidManager;
import dev.amble.core.attacks.area.BarrageManager;
import dev.amble.core.attacks.area.SlamManager;
import dev.amble.core.attacks.projectile.CrystalManager;
import dev.amble.core.attacks.projectile.DiscManager;
import dev.amble.core.attacks.projectile.PlasmaManager;
import dev.amble.core.heart.RedHeart;
import dev.amble.core.blocks.LanternRitual;
import dev.amble.core.loyalty.RingBonds;
import dev.amble.core.progression.EmotionSources;
import dev.amble.core.progression.Terror;
import dev.amble.core.progression.RingOffers;
import dev.amble.core.progression.IndigoOne;
import dev.amble.core.progression.BlueSanctuary;
import dev.amble.core.progression.Pilgrimage;
import dev.amble.core.progression.ZamaronMeteor;
import dev.amble.core.progression.SpectrumCommands;
import dev.amble.core.forge.Catalysts;
import dev.amble.core.forge.CentralPowerBattery;
import dev.amble.core.forge.ForgeHammer;
import dev.amble.core.forge.ForgeLight;
import dev.amble.core.progression.SpectrumMeters;
import dev.amble.core.progression.WorldProgress;
import dev.amble.core.ringpowers.RingBenefits;
import dev.amble.core.progression.RingRanks;
import dev.amble.core.attacks.projectile.SwarmManager;
import dev.amble.core.attacks.utility.GrappleManager;
import dev.amble.core.attacks.utility.LumberjackManager;
import dev.amble.core.attacks.utility.OreProbeManager;
import dev.amble.core.attacks.weapon.FistManager;
import dev.amble.core.attacks.weapon.TurretManager;
import dev.amble.core.attacks.weapon.WhipManager;
import dev.amble.core.drill.DrillManager;
import dev.amble.core.drill.DrillModes;
import dev.amble.core.drill.PlacedDrillManager;
import dev.amble.core.glide.GlideManager;
import dev.amble.core.ringpowers.ActiveConstructs;
import dev.amble.core.light.LightManager;
import dev.amble.core.light.LightOrbManager;
import dev.amble.core.beams.BeamManager;
import dev.amble.core.beams.HealBeamManager;
import dev.amble.core.ringpowers.CorpsSynergy;
import dev.amble.core.loyalty.RingLoyalty;
import dev.amble.core.loyalty.RingSuspension;
import dev.amble.core.team.LanternTeams;
import net.fabricmc.api.ModInitializer;

import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.Identifier;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BrightestDay implements ModInitializer {
	public static final String MOD_ID = "brightestday";

	public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

	@Override
	public void onInitialize() {
		BrightestDayConfig.load();
		BrightestDayItems.init();
		BrightestDayBlocks.init();
		BrightestDayBlockEntityTypes.init();
		BrightestDayMenus.init();
		BrightestDaySounds.init();
		BrightestDayCreativeTabs.init();
		RingPowerRegistry.init();
		BrightestDayAttachments.init();
		RingPowerTicker.init();
		Networking.init();
		FlightRingPower.registerEvents();
		ShieldManager.init();
		TractorManager.init();
		ContainmentSphere.init();
		ConstructMounts.init();
		RingSync.init();
		RingCompass.init();
		BatteryRitual.init();
		Poses.init();
		Insignia.init();
		ConstructTools.init();
		ConstructDismissal.init();
		WallManager.init();
		SculptManager.init();
		RingJumpstart.init();
		AcidManager.init();
		LightManager.init();
		LightOrbManager.init();
		BeamManager.init();
		SlamManager.init();
		BarrageManager.init();
		FistManager.init();
		WhipManager.init();
		TurretManager.init();
		SwarmManager.init();
		DiscManager.init();
		PlasmaManager.init();
		RedHeart.init();
		LanternRitual.init();
		RingBenefits.init();
		WorldProgress.init();
		RingRanks.init();
		SpectrumMeters.init();
		EmotionSources.init();
		Terror.init();
		RingOffers.init();
		RingBonds.init();
		IndigoOne.init();
		CentralPowerBattery.init();
		Mannequins.init();
		ForgeHammer.init();
		ForgeLight.init();
		Catalysts.init();
		BlueSanctuary.init();
		RedRage.init();
		CometRam.init();
		BloodHunt.init();
		Comms.init();
		Megaphone.init();
		OathCharge.init();
		Pilgrimage.init();
		ZamaronMeteor.init();
		SpectrumCommands.init();
		CrystalManager.init();
		DrillManager.init();
		PlacedDrillManager.init();
		GlideManager.init();
		ActiveConstructs.init();
		GrappleManager.init();
		LumberjackManager.init();
		OreProbeManager.init();
		DrillModes.init();
		HealBeamManager.init();
		CorpsSynergy.init();
		RingLoyalty.init();
		RingSuspension.init();
		LanternTeams.init();
	}

	public static Identifier id(String path) {
		return Identifier.fromNamespaceAndPath(MOD_ID, path);
	}
}
